"""Statement generator for MRNA Financial Services.

Generates:
1. Text summary for WhatsApp (instant delivery)
2. PDF statement for WhatsApp attachment (professional document)

Statement types: account, portfolio, loan, transaction, tax
"""
import os
import logging
from datetime import datetime, timezone
from fpdf import FPDF

logger = logging.getLogger("mrna.statement")

PDF_DIR = os.path.join(os.path.dirname(__file__), "statements")
os.makedirs(PDF_DIR, exist_ok=True)


# ---------------------------------------------------------------------------
# Text summaries (for WhatsApp message body)
# ---------------------------------------------------------------------------

async def generate_account_summary(customer_id: str) -> str:
    from db.database import get_customer, get_customer_loans, get_customer_portfolios, get_customer_tickets
    cust = await get_customer(customer_id)
    if not cust:
        return "Customer not found."

    loans = await get_customer_loans(customer_id)
    portfolios = await get_customer_portfolios(customer_id)
    tickets = await get_customer_tickets(customer_id)

    active_loans = [l for l in loans if l.get("status") == "active"]
    total_outstanding = sum(float(l.get("outstanding", 0) or 0) for l in active_loans)
    total_invested = sum(float(p.get("total_invested", 0) or 0) for p in portfolios)
    total_current = sum(float(p.get("current_value", 0) or 0) for p in portfolios)
    open_tickets = [t for t in tickets if t.get("status") not in ("resolved", "closed")]

    lines = [
        f"*Account Statement - MRNA*",
        f"Date: {datetime.now().strftime('%d %b %Y')}",
        f"",
        f"*Customer:* {cust.get('name', 'N/A')}",
        f"*ID:* {customer_id} | *Segment:* {cust.get('segment', 'N/A')}",
        f"*KYC Status:* {cust.get('kyc_status', 'N/A')}",
        f"",
        f"*Loans ({len(active_loans)} active):*",
        f"  Total Outstanding: SAR {total_outstanding:,.0f}",
    ]
    for l in active_loans:
        lines.append(f"  - {l.get('type','').title()} ({l['id']}): SAR {float(l.get('outstanding',0) or 0):,.0f}")

    lines += [
        f"",
        f"*Investments ({len(portfolios)} portfolios):*",
        f"  Total Invested: SAR {total_invested:,.0f}",
        f"  Current Value: SAR {total_current:,.0f}",
        f"  P&L: SAR {total_current - total_invested:+,.0f}",
    ]
    for p in portfolios:
        val = float(p.get("current_value", 0) or 0)
        lines.append(f"  - {p.get('name', p['id'])}: SAR {val:,.0f}")

    if open_tickets:
        lines += [f"", f"*Open Tickets:* {len(open_tickets)}"]
        for t in open_tickets[:3]:
            lines.append(f"  - {t['id']}: {t.get('subject', 'N/A')}")

    lines += [f"", f"_Generated by MRNA on {datetime.now().strftime('%d %b %Y %H:%M')}_"]
    return "\n".join(lines)


async def generate_loan_summary(customer_id: str) -> str:
    from db.database import get_customer, get_customer_loans, get_payment_history, get_next_emi
    cust = await get_customer(customer_id)
    if not cust:
        return "Customer not found."

    loans = await get_customer_loans(customer_id)
    if not loans:
        return "No loans found."

    lines = [
        f"*Loan Statement - MRNA*",
        f"Date: {datetime.now().strftime('%d %b %Y')}",
        f"Customer: {cust.get('name', 'N/A')} ({customer_id})",
        f"",
    ]

    for loan in loans:
        lid = loan["id"]
        lines += [
            f"*{loan.get('type','').title()} Loan ({lid})*",
            f"  Status: {loan.get('status', 'N/A')}",
            f"  Principal: SAR {float(loan.get('principal', 0) or 0):,.0f}",
            f"  Outstanding: SAR {float(loan.get('outstanding', 0) or 0):,.0f}",
            f"  Rate: {loan.get('interest_rate', 'N/A')}%",
            f"  Tenure: {loan.get('tenure_months', 'N/A')} months",
        ]
        try:
            nxt = await get_next_emi(lid)
            if nxt:
                lines.append(f"  Next EMI: SAR {float(nxt.get('amount', 0) or 0):,.0f} on {str(nxt.get('due_date', 'N/A'))[:10]}")
        except Exception:
            pass

        try:
            payments = await get_payment_history(lid, limit=3)
            if payments:
                lines.append(f"  Recent payments:")
                for p in payments:
                    lines.append(f"    {str(p.get('due_date',''))[:10]}: SAR {float(p.get('amount',0) or 0):,.0f} [{p.get('status','N/A')}]")
        except Exception:
            pass
        lines.append("")

    lines.append(f"_Generated by MRNA on {datetime.now().strftime('%d %b %Y %H:%M')}_")
    return "\n".join(lines)


async def generate_portfolio_summary(customer_id: str) -> str:
    from db.database import (
        get_customer, get_customer_portfolios, get_holdings,
        get_sips, get_dividends
    )
    cust = await get_customer(customer_id)
    if not cust:
        return "Customer not found."

    portfolios = await get_customer_portfolios(customer_id)
    if not portfolios:
        return "No portfolios found."

    lines = [
        f"*Portfolio Statement - MRNA*",
        f"Date: {datetime.now().strftime('%d %b %Y')}",
        f"Customer: {cust.get('name', 'N/A')} ({customer_id})",
        f"",
    ]

    grand_invested = 0
    grand_current = 0

    for port in portfolios:
        pid = port["id"]
        invested = float(port.get("total_invested", 0) or 0)
        current = float(port.get("current_value", 0) or 0)
        grand_invested += invested
        grand_current += current
        pnl = current - invested
        pnl_pct = (pnl / invested * 100) if invested else 0

        lines += [
            f"*{port.get('name', pid)}* ({port.get('type', 'N/A')})",
            f"  Invested: SAR {invested:,.0f} | Current: SAR {current:,.0f}",
            f"  P&L: SAR {pnl:+,.0f} ({pnl_pct:+.1f}%)",
        ]

        try:
            holdings = await get_holdings(pid)
            if holdings:
                lines.append(f"  Holdings ({len(holdings)}):")
                for h in holdings:
                    units = float(h.get("units", 0) or 0)
                    nav = float(h.get("current_nav", 0) or 0)
                    val = units * nav
                    lines.append(f"    - {h.get('fund_name', h.get('fund_id', 'N/A'))}: {units:,.2f} units @ SAR {nav:,.2f} = SAR {val:,.0f}")
        except Exception:
            pass

        try:
            sips = await get_sips(pid)
            active_sips = [s for s in sips if s.get("status") == "active"]
            if active_sips:
                lines.append(f"  Active SIPs:")
                for s in active_sips:
                    lines.append(f"    - SAR {float(s.get('amount',0) or 0):,.0f}/month into {s.get('fund_name', s.get('fund_id', 'N/A'))}")
        except Exception:
            pass

        try:
            divs = await get_dividends(pid)
            if divs:
                total_div = sum(float(d.get("amount", 0) or 0) for d in divs)
                lines.append(f"  Dividends received: SAR {total_div:,.0f} ({len(divs)} payments)")
        except Exception:
            pass

        lines.append("")

    pnl_total = grand_current - grand_invested
    lines += [
        f"*Total Portfolio*",
        f"  Invested: SAR {grand_invested:,.0f}",
        f"  Current Value: SAR {grand_current:,.0f}",
        f"  Total P&L: SAR {pnl_total:+,.0f} ({(pnl_total/grand_invested*100) if grand_invested else 0:+.1f}%)",
        f"",
        f"_Generated by MRNA on {datetime.now().strftime('%d %b %Y %H:%M')}_",
    ]
    return "\n".join(lines)


async def generate_transaction_summary(customer_id: str) -> str:
    from db.database import get_customer, get_customer_portfolios, get_transactions
    cust = await get_customer(customer_id)
    if not cust:
        return "Customer not found."

    portfolios = await get_customer_portfolios(customer_id)
    if not portfolios:
        return "No portfolios found."

    lines = [
        f"*Transaction Statement - MRNA*",
        f"Date: {datetime.now().strftime('%d %b %Y')}",
        f"Customer: {cust.get('name', 'N/A')} ({customer_id})",
        f"",
    ]

    for port in portfolios:
        pid = port["id"]
        txns = await get_transactions(pid, limit=10)
        if not txns:
            continue
        lines.append(f"*{port.get('name', pid)}*:")
        for t in txns:
            amt = float(t.get("amount", 0) or 0)
            date = str(t.get("executed_at", ""))[:10]
            lines.append(f"  {date} | {t.get('type','N/A').upper()} | {t.get('fund_name', t.get('fund_id','N/A'))} | SAR {amt:,.0f} | {t.get('status','N/A')}")
        lines.append("")

    lines.append(f"_Generated by MRNA on {datetime.now().strftime('%d %b %Y %H:%M')}_")
    return "\n".join(lines)


async def generate_tax_summary(customer_id: str) -> str:
    from db.database import (
        get_customer, get_customer_portfolios, get_transactions,
        get_dividends, get_customer_loans
    )
    cust = await get_customer(customer_id)
    if not cust:
        return "Customer not found."

    portfolios = await get_customer_portfolios(customer_id)
    loans = await get_customer_loans(customer_id)

    total_dividends = 0
    total_gains = 0
    total_interest = 0

    for port in portfolios:
        divs = await get_dividends(port["id"])
        total_dividends += sum(float(d.get("amount", 0) or 0) for d in divs)
        txns = await get_transactions(port["id"])
        sells = [t for t in txns if t.get("type") in ("sell", "switch_out")]
        total_gains += sum(float(t.get("amount", 0) or 0) for t in sells)

    for loan in loans:
        total_interest += float(loan.get("interest_rate", 0) or 0) * float(loan.get("principal", 0) or 0) / 100

    lines = [
        f"*Tax Summary - MRNA*",
        f"Date: {datetime.now().strftime('%d %b %Y')}",
        f"Customer: {cust.get('name', 'N/A')} ({customer_id})",
        f"",
        f"*Income:*",
        f"  Dividends Received: SAR {total_dividends:,.0f}",
        f"  Realized Gains (sells): SAR {total_gains:,.0f}",
        f"",
        f"*Deductible:*",
        f"  Estimated Loan Interest: SAR {total_interest:,.0f}",
        f"",
        f"Note: This is an indicative summary. Consult your tax advisor for ZATCA compliance.",
        f"",
        f"_Generated by MRNA on {datetime.now().strftime('%d %b %Y %H:%M')}_",
    ]
    return "\n".join(lines)


# Map type -> generator
SUMMARY_GENERATORS = {
    "account": generate_account_summary,
    "loan": generate_loan_summary,
    "portfolio": generate_portfolio_summary,
    "transaction": generate_transaction_summary,
    "tax": generate_tax_summary,
}


async def generate_text_summary(customer_id: str, statement_type: str) -> str:
    gen = SUMMARY_GENERATORS.get(statement_type)
    if not gen:
        return f"Unknown statement type: {statement_type}"
    return await gen(customer_id)


# ---------------------------------------------------------------------------
# PDF generation
# ---------------------------------------------------------------------------

class StatementPDF(FPDF):
    """Branded MRNA statement PDF."""

    def __init__(self, title: str, customer_name: str, customer_id: str):
        super().__init__()
        self._title = title
        self._customer_name = customer_name
        self._customer_id = customer_id
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Brand bar
        self.set_fill_color(15, 82, 186)  # MRNA blue
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 4)
        self.cell(0, 10, "MRNA Financial Services", align="L")
        self.set_font("Helvetica", "", 9)
        self.set_xy(10, 11)
        self.cell(0, 5, self._title, align="L")

        # Date on right
        self.set_xy(-60, 4)
        self.set_font("Helvetica", "", 9)
        self.cell(50, 10, datetime.now().strftime("%d %B %Y"), align="R")

        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"MRNA Financial Services | Confidential | Page {self.page_no()}/{{nb}}", align="C")

    def add_customer_info(self, customer: dict):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(60, 60, 60)
        self.cell(0, 5, f"Customer: {customer.get('name', 'N/A')} ({self._customer_id}) | Segment: {customer.get('segment', 'N/A')} | KYC: {customer.get('kyc_status', 'N/A')}", ln=True)
        self.ln(3)

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(15, 82, 186)
        self.cell(0, 8, title, ln=True)
        self.set_draw_color(15, 82, 186)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)

    def kv_row(self, key: str, value: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(80, 80, 80)
        self.cell(55, 5, key, align="L")
        self.set_text_color(30, 30, 30)
        self.set_font("Helvetica", "B", 9)
        self.cell(0, 5, value, ln=True)

    def table_header(self, cols: list, widths: list):
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(240, 243, 250)
        self.set_text_color(30, 30, 30)
        for c, w in zip(cols, widths):
            self.cell(w, 6, c, border=0, fill=True, align="C")
        self.ln()

    def table_row(self, cells: list, widths: list, aligns: list = None):
        self.set_font("Helvetica", "", 8)
        self.set_text_color(50, 50, 50)
        if not aligns:
            aligns = ["L"] * len(cells)
        for c, w, a in zip(cells, widths, aligns):
            self.cell(w, 5, str(c), border=0, align=a)
        self.ln()

    def summary_box(self, items: list):
        """items: list of (label, value) tuples shown in a highlight box."""
        self.set_fill_color(245, 248, 255)
        y = self.get_y()
        box_w = 190
        box_h = 8 * len(items) + 4
        self.rect(10, y, box_w, box_h, "F")
        self.set_xy(14, y + 2)
        for label, value in items:
            self.set_font("Helvetica", "", 9)
            self.set_text_color(80, 80, 80)
            self.cell(50, 7, label)
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(15, 82, 186)
            self.cell(0, 7, value, ln=True)
            self.set_x(14)
        self.ln(3)


def _safe(val, default="N/A"):
    if val is None:
        return default
    return str(val)


def _sar(val):
    try:
        return f"SAR {float(val):,.0f}"
    except (TypeError, ValueError):
        return "SAR 0"


async def generate_account_pdf(customer_id: str) -> str:
    from db.database import get_customer, get_customer_loans, get_customer_portfolios, get_customer_tickets
    cust = await get_customer(customer_id)
    if not cust:
        return ""

    loans = await get_customer_loans(customer_id)
    portfolios = await get_customer_portfolios(customer_id)
    tickets = await get_customer_tickets(customer_id)

    active_loans = [l for l in loans if l.get("status") == "active"]
    total_outstanding = sum(float(l.get("outstanding", 0) or 0) for l in active_loans)
    total_invested = sum(float(p.get("total_invested", 0) or 0) for p in portfolios)
    total_current = sum(float(p.get("current_value", 0) or 0) for p in portfolios)

    pdf = StatementPDF("Account Statement", cust.get("name", "N/A"), customer_id)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_customer_info(cust)

    # Summary box
    pdf.summary_box([
        ("Active Loans", f"{len(active_loans)} | Outstanding: {_sar(total_outstanding)}"),
        ("Portfolios", f"{len(portfolios)} | Value: {_sar(total_current)}"),
        ("Net Position", _sar(total_current - total_outstanding)),
    ])

    # Loans table
    if loans:
        pdf.section_title("Loans")
        widths = [25, 25, 35, 35, 35, 35]
        pdf.table_header(["ID", "Type", "Principal", "Outstanding", "Rate", "Status"], widths)
        for l in loans:
            pdf.table_row([
                l["id"], _safe(l.get("type", "")).title(),
                _sar(l.get("principal")), _sar(l.get("outstanding")),
                f"{_safe(l.get('interest_rate'))}%", _safe(l.get("status", "")).title()
            ], widths, ["L", "L", "R", "R", "R", "C"])
        pdf.ln(5)

    # Portfolios table
    if portfolios:
        pdf.section_title("Investment Portfolios")
        widths = [25, 40, 30, 35, 35, 25]
        pdf.table_header(["ID", "Name", "Type", "Invested", "Current", "P&L %"], widths)
        for p in portfolios:
            inv = float(p.get("total_invested", 0) or 0)
            cur = float(p.get("current_value", 0) or 0)
            pnl_pct = ((cur - inv) / inv * 100) if inv else 0
            pdf.table_row([
                p["id"], _safe(p.get("name")), _safe(p.get("type", "")).title(),
                _sar(inv), _sar(cur), f"{pnl_pct:+.1f}%"
            ], widths, ["L", "L", "C", "R", "R", "R"])
        pdf.ln(5)

    # Open tickets
    open_tickets = [t for t in tickets if t.get("status") not in ("resolved", "closed")]
    if open_tickets:
        pdf.section_title("Open Support Tickets")
        widths = [30, 60, 30, 30, 40]
        pdf.table_header(["ID", "Subject", "Priority", "Status", "Created"], widths)
        for t in open_tickets:
            pdf.table_row([
                t["id"], _safe(t.get("subject"))[:35],
                _safe(t.get("priority", "")).title(), _safe(t.get("status", "")).title(),
                str(t.get("created_at", ""))[:10]
            ], widths, ["L", "L", "C", "C", "C"])

    path = os.path.join(PDF_DIR, f"account_{customer_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")
    pdf.output(path)
    logger.info(f"Account PDF generated: {path}")
    return path


async def generate_loan_pdf(customer_id: str) -> str:
    from db.database import get_customer, get_customer_loans, get_payment_history, get_next_emi
    cust = await get_customer(customer_id)
    if not cust:
        return ""

    loans = await get_customer_loans(customer_id)
    if not loans:
        return ""

    pdf = StatementPDF("Loan Statement", cust.get("name", "N/A"), customer_id)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_customer_info(cust)

    for loan in loans:
        lid = loan["id"]
        pdf.section_title(f"{_safe(loan.get('type','')).title()} Loan - {lid}")

        pdf.kv_row("Status", _safe(loan.get("status", "")).title())
        pdf.kv_row("Principal", _sar(loan.get("principal")))
        pdf.kv_row("Outstanding Balance", _sar(loan.get("outstanding")))
        pdf.kv_row("Interest Rate", f"{_safe(loan.get('interest_rate'))}% p.a.")
        pdf.kv_row("Tenure", f"{_safe(loan.get('tenure_months'))} months")
        pdf.kv_row("Start Date", str(loan.get("start_date", "N/A"))[:10])

        try:
            nxt = await get_next_emi(lid)
            if nxt:
                pdf.kv_row("Next EMI", f"{_sar(nxt.get('amount'))} due {str(nxt.get('due_date',''))[:10]}")
        except Exception:
            pass

        pdf.ln(3)

        try:
            payments = await get_payment_history(lid, limit=12)
            if payments:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(60, 60, 60)
                pdf.cell(0, 6, "Payment History", ln=True)
                widths = [30, 35, 35, 35, 55]
                pdf.table_header(["Due Date", "Amount", "Paid", "Late Fee", "Status"], widths)
                for p in payments:
                    pdf.table_row([
                        str(p.get("due_date", ""))[:10],
                        _sar(p.get("amount")),
                        _sar(p.get("paid_amount", p.get("amount"))),
                        _sar(p.get("late_fee", 0)),
                        _safe(p.get("status", "")).title()
                    ], widths, ["C", "R", "R", "R", "C"])
        except Exception:
            pass
        pdf.ln(5)

    path = os.path.join(PDF_DIR, f"loan_{customer_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")
    pdf.output(path)
    logger.info(f"Loan PDF generated: {path}")
    return path


async def generate_portfolio_pdf(customer_id: str) -> str:
    from db.database import (
        get_customer, get_customer_portfolios, get_holdings,
        get_sips, get_dividends
    )
    cust = await get_customer(customer_id)
    if not cust:
        return ""

    portfolios = await get_customer_portfolios(customer_id)
    if not portfolios:
        return ""

    pdf = StatementPDF("Portfolio Statement", cust.get("name", "N/A"), customer_id)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_customer_info(cust)

    grand_invested = sum(float(p.get("total_invested", 0) or 0) for p in portfolios)
    grand_current = sum(float(p.get("current_value", 0) or 0) for p in portfolios)
    pnl = grand_current - grand_invested

    pdf.summary_box([
        ("Total Invested", _sar(grand_invested)),
        ("Current Value", _sar(grand_current)),
        ("Total P&L", f"{_sar(pnl)} ({(pnl/grand_invested*100) if grand_invested else 0:+.1f}%)"),
    ])

    for port in portfolios:
        pid = port["id"]
        inv = float(port.get("total_invested", 0) or 0)
        cur = float(port.get("current_value", 0) or 0)

        pdf.section_title(f"{_safe(port.get('name', pid))} ({_safe(port.get('type','')).title()})")
        pdf.kv_row("Invested", _sar(inv))
        pdf.kv_row("Current Value", _sar(cur))
        pdf.kv_row("P&L", f"{_sar(cur - inv)} ({((cur-inv)/inv*100) if inv else 0:+.1f}%)")
        pdf.ln(2)

        try:
            holdings = await get_holdings(pid)
            if holdings:
                widths = [50, 25, 30, 30, 30, 25]
                pdf.table_header(["Fund", "Units", "Avg Buy", "NAV", "Value", "P&L %"], widths)
                for h in holdings:
                    units = float(h.get("units", 0) or 0)
                    avg = float(h.get("avg_buy_price", 0) or 0)
                    nav = float(h.get("current_nav", 0) or 0)
                    val = units * nav
                    cost = units * avg
                    hpnl = ((val - cost) / cost * 100) if cost else 0
                    pdf.table_row([
                        _safe(h.get("fund_name", h.get("fund_id")))[:28],
                        f"{units:,.2f}", _sar(avg), _sar(nav), _sar(val), f"{hpnl:+.1f}%"
                    ], widths, ["L", "R", "R", "R", "R", "R"])
                pdf.ln(3)
        except Exception:
            pass

        try:
            sips = await get_sips(pid)
            active_sips = [s for s in sips if s.get("status") == "active"]
            if active_sips:
                pdf.set_font("Helvetica", "B", 9)
                pdf.cell(0, 6, "Active SIPs", ln=True)
                widths = [50, 35, 30, 35, 40]
                pdf.table_header(["Fund", "Amount/Month", "Day", "Invested", "Status"], widths)
                for s in active_sips:
                    pdf.table_row([
                        _safe(s.get("fund_name", s.get("fund_id")))[:28],
                        _sar(s.get("amount")),
                        _safe(s.get("day_of_month")),
                        _sar(s.get("total_invested")),
                        "Active"
                    ], widths, ["L", "R", "C", "R", "C"])
                pdf.ln(3)
        except Exception:
            pass

        try:
            divs = await get_dividends(pid)
            if divs:
                total_div = sum(float(d.get("amount", 0) or 0) for d in divs)
                pdf.set_font("Helvetica", "B", 9)
                pdf.cell(0, 6, f"Dividends (Total: {_sar(total_div)})", ln=True)
                widths = [50, 35, 35, 35, 35]
                pdf.table_header(["Fund", "Amount", "NAV", "Units Added", "Date"], widths)
                for d in divs:
                    pdf.table_row([
                        _safe(d.get("fund_name", d.get("fund_id")))[:28],
                        _sar(d.get("amount")),
                        _sar(d.get("nav_at_dividend")),
                        f"{float(d.get('units_added', 0) or 0):,.2f}",
                        str(d.get("dividend_date", ""))[:10]
                    ], widths, ["L", "R", "R", "R", "C"])
                pdf.ln(3)
        except Exception:
            pass
        pdf.ln(3)

    path = os.path.join(PDF_DIR, f"portfolio_{customer_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")
    pdf.output(path)
    logger.info(f"Portfolio PDF generated: {path}")
    return path


async def generate_transaction_pdf(customer_id: str) -> str:
    from db.database import get_customer, get_customer_portfolios, get_transactions
    cust = await get_customer(customer_id)
    if not cust:
        return ""

    portfolios = await get_customer_portfolios(customer_id)
    if not portfolios:
        return ""

    pdf = StatementPDF("Transaction Statement", cust.get("name", "N/A"), customer_id)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_customer_info(cust)

    for port in portfolios:
        pid = port["id"]
        txns = await get_transactions(pid, limit=20)
        if not txns:
            continue

        pdf.section_title(f"{_safe(port.get('name', pid))}")
        widths = [25, 20, 40, 30, 30, 25, 20]
        pdf.table_header(["Date", "Type", "Fund", "Amount", "Units", "NAV", "Status"], widths)
        for t in txns:
            pdf.table_row([
                str(t.get("executed_at", ""))[:10],
                _safe(t.get("type", "")).upper(),
                _safe(t.get("fund_name", t.get("fund_id")))[:22],
                _sar(t.get("amount")),
                f"{float(t.get('units', 0) or 0):,.2f}",
                _sar(t.get("nav")),
                _safe(t.get("status", "")).title()[:8]
            ], widths, ["C", "C", "L", "R", "R", "R", "C"])
        pdf.ln(5)

    path = os.path.join(PDF_DIR, f"transactions_{customer_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")
    pdf.output(path)
    logger.info(f"Transaction PDF generated: {path}")
    return path


async def generate_tax_pdf(customer_id: str) -> str:
    """Tax summary - simplified version."""
    from db.database import (
        get_customer, get_customer_portfolios, get_transactions,
        get_dividends, get_customer_loans
    )
    cust = await get_customer(customer_id)
    if not cust:
        return ""

    pdf = StatementPDF("Tax Summary", cust.get("name", "N/A"), customer_id)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_customer_info(cust)

    portfolios = await get_customer_portfolios(customer_id)
    loans = await get_customer_loans(customer_id)

    total_dividends = 0
    total_gains = 0

    for port in portfolios:
        divs = await get_dividends(port["id"])
        total_dividends += sum(float(d.get("amount", 0) or 0) for d in divs)
        txns = await get_transactions(port["id"])
        sells = [t for t in txns if t.get("type") in ("sell", "switch_out")]
        total_gains += sum(float(t.get("amount", 0) or 0) for t in sells)

    total_interest = sum(
        float(l.get("interest_rate", 0) or 0) * float(l.get("principal", 0) or 0) / 100
        for l in loans
    )

    pdf.section_title("Income Summary")
    pdf.kv_row("Dividends Received", _sar(total_dividends))
    pdf.kv_row("Realized Gains (Sells)", _sar(total_gains))
    pdf.kv_row("Total Taxable Income", _sar(total_dividends + total_gains))
    pdf.ln(5)

    pdf.section_title("Deductible Items")
    pdf.kv_row("Estimated Loan Interest", _sar(total_interest))
    pdf.ln(5)

    pdf.section_title("Disclaimer")
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 4, "This is an indicative tax summary only. It does not constitute tax advice. Please consult your tax advisor for ZATCA compliance and final tax filing. MRNA Financial Services is not responsible for tax calculations or filings.")

    path = os.path.join(PDF_DIR, f"tax_{customer_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")
    pdf.output(path)
    logger.info(f"Tax PDF generated: {path}")
    return path


# Map type -> PDF generator
PDF_GENERATORS = {
    "account": generate_account_pdf,
    "loan": generate_loan_pdf,
    "portfolio": generate_portfolio_pdf,
    "transaction": generate_transaction_pdf,
    "tax": generate_tax_pdf,
}


async def generate_pdf(customer_id: str, statement_type: str) -> str:
    """Generate PDF and return file path. Empty string on failure."""
    gen = PDF_GENERATORS.get(statement_type)
    if not gen:
        return ""
    try:
        return await gen(customer_id)
    except Exception as e:
        logger.error(f"PDF generation failed ({statement_type}): {e}")
        return ""
