"""WhatsApp client via local HTTP relay (port 8097) -> OpenClaw gateway."""
import logging
import asyncio
import json

logger = logging.getLogger("mrna.wa")

RELAY_URL = "http://127.0.0.1:8097"


async def _send_via_relay(phone: str, message: str) -> bool:
    """Send WhatsApp message via local Node.js relay."""
    try:
        import aiohttp
        payload = json.dumps({
            "target": phone,
            "message": message,
            "channel": "whatsapp",
        })
        async with aiohttp.ClientSession() as session:
            async with session.post(RELAY_URL, data=payload,
                                     headers={"Content-Type": "application/json"},
                                     timeout=aiohttp.ClientTimeout(total=20)) as resp:
                if resp.status == 200:
                    logger.info(f"WA sent to {phone}: OK (msg_len={len(message)})")
                    return True
                else:
                    body = await resp.text()
                    logger.warning(f"WA relay failed ({resp.status}): {body[:200]}")
                    return False
    except Exception as e:
        logger.warning(f"WA send error: {e}")
        return False


async def send_otp(phone: str, code: str, customer_name: str = "") -> bool:
    message = f"MRNA Security Code: {code} (valid 5 minutes). Do not share this code with anyone."
    return await _send_via_relay(phone, message)


async def send_call_summary(phone: str, customer_name: str, summary: str) -> bool:
    message = (
        f"*Call Summary - MRNA*\n\n"
        f"Hello {customer_name},\n\n"
        f"{summary}\n\n"
        f"For queries, reply to this message or call us.\n"
        f"_MRNA Financial Services_"
    )
    return await _send_via_relay(phone, message)


async def send_statement_notification(phone: str, customer_name: str, statement_type: str) -> bool:
    import datetime
    message = (
        f"*Statement Ready - MRNA*\n\n"
        f"Hello {customer_name},\n\n"
        f"Your {statement_type} statement has been generated.\n\n"
        f"_Generated by MRNA on {datetime.date.today()}_"
    )
    return await _send_via_relay(phone, message)


async def send_message(phone: str, message: str) -> bool:
    return await _send_via_relay(phone, message)


async def wa_status() -> str:
    return "connected"
