"""WhatsApp client via OpenClaw gateway â€” sends OTPs, summaries, statements."""
import os
import logging
import asyncio
import json

logger = logging.getLogger("mrna.wa")


async def _send_via_openclaw(phone: str, message: str) -> bool:
    """Send WhatsApp message via OpenClaw CLI."""
    try:
        proc = await asyncio.create_subprocess_exec(
            r"C:\Users\AI\AppData\Roaming\npm\openclaw.cmd", "message", "send",
            "--target", phone,
            "--message", message,
            "--channel", "whatsapp",
            "--json",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=15)
        if proc.returncode == 0:
            logger.info(f"WA sent to {phone}: OK")
            return True
        else:
            err = stderr.decode().strip() if stderr else "unknown"
            logger.warning(f"WA send failed ({proc.returncode}): {err}")
            return False
    except asyncio.TimeoutError:
        logger.warning(f"WA send to {phone} timed out")
        return False
    except Exception as e:
        logger.warning(f"WA send error: {e}")
        return False


async def send_otp(phone: str, code: str, customer_name: str = "") -> bool:
    """Send OTP to customer WhatsApp."""
    message = f"MRNA Security Code: {code} (valid 5 minutes). Do not share this code with anyone."
    return await _send_via_openclaw(phone, message)


async def send_call_summary(phone: str, customer_name: str, summary: str) -> bool:
    """Send post-call summary to customer WhatsApp."""
    message = (
        f"*Call Summary - MRNA*\n\n"
        f"Hello {customer_name},\n\n"
        f"{summary}\n\n"
        f"For queries, reply to this message or call us.\n"
        f"_MRNA Financial Services_"
    )
    return await _send_via_openclaw(phone, message)


async def send_statement_notification(phone: str, customer_name: str, statement_type: str) -> bool:
    """Notify customer their statement is ready via WhatsApp."""
    message = (
        f"*Statement Ready - MRNA*\n\n"
        f"Hello {customer_name},\n\n"
        f"Your {statement_type} statement has been generated.\n\n"
        f"_Generated by MRNA on {__import__('datetime').date.today()}_"
    )
    return await _send_via_openclaw(phone, message)


async def send_message(phone: str, message: str) -> bool:
    """Send arbitrary message via WhatsApp."""
    return await _send_via_openclaw(phone, message)


async def wa_status() -> str:
    """Get WhatsApp status â€” always connected via OpenClaw."""
    return "connected"


