"""WhatsApp client via OpenClaw gateway -- sends OTPs, summaries, statements."""
import os
import logging
import asyncio
import json
import tempfile

logger = logging.getLogger("mrna.wa")

OPENCLAW_CMD = r"C:\Users\AI\AppData\Roaming\npm\openclaw.cmd"


async def _send_via_openclaw(phone: str, message: str) -> bool:
    """Send WhatsApp message via OpenClaw CLI.
    
    Uses a temp file for the message body to avoid CLI arg truncation
    with multiline messages on Windows.
    """
    tmp_path = None
    try:
        # Write message to temp file to avoid CLI arg issues with newlines
        with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False, encoding='utf-8') as f:
            f.write(message)
            tmp_path = f.name
        
        # Use --file flag if available, otherwise read file and pass as arg
        # Test: try with file content piped via powershell
        ps_cmd = (
            f'$msg = Get-Content -Path "{tmp_path}" -Raw -Encoding utf8; '
            f'& "{OPENCLAW_CMD}" message send '
            f'--target "{phone}" '
            f'--message $msg '
            f'--channel whatsapp '
            f'--json'
        )
        
        proc = await asyncio.create_subprocess_exec(
            "powershell", "-NoProfile", "-Command", ps_cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=20)
        
        if proc.returncode == 0:
            logger.info(f"WA sent to {phone}: OK (msg_len={len(message)})")
            return True
        else:
            err = stderr.decode(errors='replace').strip() if stderr else "unknown"
            logger.warning(f"WA send failed ({proc.returncode}): {err[:200]}")
            return False
    except asyncio.TimeoutError:
        logger.warning(f"WA send to {phone} timed out")
        return False
    except Exception as e:
        logger.warning(f"WA send error: {e}")
        return False
    finally:
        if tmp_path:
            try:
                os.unlink(tmp_path)
            except Exception:
                pass


async def send_otp(phone: str, code: str, customer_name: str = "") -> bool:
    """Send OTP to customer WhatsApp."""
    message = f"MRNA Security Code: {code} (valid 5 minutes). Do not share this code with anyone."
    return await _send_via_openclaw(phone, message)


async def send_call_summary(phone: str, customer_name: str, summary: str) -> bool:
    """Send post-call summary to customer WhatsApp."""
    message = (
        f"*Call Summary - MRNA*\n\n"
        f"Hello {customer_name},\n\n"
        f"{summary}\n\n"
        f"For queries, reply to this message or call us.\n"
        f"_MRNA Financial Services_"
    )
    return await _send_via_openclaw(phone, message)


async def send_statement_notification(phone: str, customer_name: str, statement_type: str) -> bool:
    """Notify customer their statement is ready via WhatsApp."""
    import datetime
    message = (
        f"*Statement Ready - MRNA*\n\n"
        f"Hello {customer_name},\n\n"
        f"Your {statement_type} statement has been generated.\n\n"
        f"_Generated by MRNA on {datetime.date.today()}_"
    )
    return await _send_via_openclaw(phone, message)


async def send_message(phone: str, message: str) -> bool:
    """Send arbitrary message via WhatsApp."""
    return await _send_via_openclaw(phone, message)


async def wa_status() -> str:
    """Get WhatsApp status -- always connected via OpenClaw."""
    return "connected"
